import Header from "@/components/pages/layout/Header";
import NavigateSection from "@/components/pages/layout/NavigateSection";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <section className=" flex w-full h-full overflow-hidden">
      <NavigateSection />
      <section className="w-full max-h-[100vh]">
        <Header position="detail" />
        {children}
      </section>
    </section>
  );
}
