import Header from "@/components/pages/layout/Header";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <section className="w-full h-[100vh] overflow-hidden">
      <Header position="study" />
      {children}
    </section>
  );
}
