import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AuthProvider } from "@/context/AuthContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko" className={inter.className}>
      <body className="flex flex-col w-[100vw] h-[100vh] max-w-screen-2xl mx-auto">
        <AuthProvider>
          <main className="grow w-full ">{children}</main>
        </AuthProvider>
      </body>
    </html>
  );
}
