import Header from "@/components/Header";
import NavigateSection from "@/components/NavigateSection";
import SWRContext from "@/context/SWRContext";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <SWRContext>
      <section className=" flex w-full h-full overflow-hidden">
        <NavigateSection />
        <section className="w-full max-h-[100vh]">
          <Header />
          {children}
        </section>
      </section>
    </SWRContext>
  );
}
