import Header from "@/components/Header";
import NavigateSection from "@/components/NavigateSection";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <section className=" ">
      <Header />
      {children}
    </section>
  );
}
