import Header from "@/components/Header";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <section className="w-full h-[100vh] overflow-hidden">
      <Header position="study" />
      {/* <div className="w-10 h-full bg-slate-100 border-r-2"></div> */}
      {children}
    </section>
  );
}
