export { default as Brain } from "./icons/Brain";
export { default as Book } from "./icons/Book";
export { default as Instudy } from "./icons/Instudy";
export { default as Own } from "./icons/Own";
export { default as Complete } from "./icons/Complete";
export { default as ArrowLeft } from "./icons/ArrowLeft";
export { default as ArrowRight } from "./icons/ArrowRight";
export { default as BackArrow } from "./icons/BackArrow";
export { default as Loading } from "./icons/Loading";
